apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot-microservice
spec:
  clusterIP: None  # This makes it a headless service
  ports:
  - port: 8080
  selector:
    app: springboot-microservice