# STAGE: Build
FROM gradle:7.5.0-jdk11 as builder

# Set Environment Variables for Build
ENV BUILD_DIR=/home/build

# Create Working Directory and Copy Build Files
RUN mkdir $BUILD_DIR
WORKDIR $BUILD_DIR
COPY build.gradle settings.gradle ./

# Download Dependencies
RUN gradle dependencies

# Copy Source and Build Application
COPY src src
RUN gradle build -x test --continue && \
    mv build/libs/*-SNAPSHOT.jar build/libs/app.jar

# STAGE: Deploy
FROM openjdk:11-jre-slim-buster

# Set Environment Variables for Deploy
ENV USERNAME=appuser \
    GROUP=appuser \
    USER_UID=1001 \
    USER_GID=1001 \
    APP_HOME=/home/app

# Setup Non-Root environment and Copy JAR
RUN mkdir -p $APP_HOME && \
    addgroup --gid $USER_GID $GROUP && \
    adduser --uid $USER_UID --gid $USER_GID $USERNAME

WORKDIR $APP_HOME
COPY --from=builder --chown=$USER_UID:$USER_GID /home/build/build/libs/app.jar ./
RUN chmod 700 app.jar

# Switch to Non-root user and Expose Port
USER $USERNAME
EXPOSE 8080

CMD ["java", "-jar", "./app.jar"]