apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-microservice
  name: springboot-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
      - command:
        - java
        - -Djava.io.tmpdir=/spring-tmp
        - -jar
        - ./app.jar
        - --spring.config.location=/config/application.properties,/secret/application.properties
        env:
        - name: SERVER_PORT
          value: "8080"
        image: springboot-microservice:maven
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 35
          periodSeconds: 20
        name: springboot-microservice
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          limits:
            memory: 192Mi
          requests:
            cpu: "0.5"
            memory: 192Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /spring-tmp
          name: spring-tmp
        - mountPath: /config
          name: config-volume
        - mountPath: /secret
          name: secret-volume  # Mounting the secret as another volume
      imagePullSecrets:
      - name: artifactory
      volumes:
      - emptyDir:
          medium: Memory
        name: spring-tmp
      - name: config-volume
        configMap:
          name: springboot-microservice-config
      - name: secret-volume  # Defining the secret as another volume
        secret:
          secretName: springboot-microservice-secret