apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-microservice
  name: springboot-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
      - args:
        - -jar
        - ./app.jar
        - --spring.config.location=file:///config/application.properties,file:///secret/application.properties  # 5. Specify the locations of the ConfigMap and Secret
        command:
        - java
        image: springboot-microservice:maven
        imagePullPolicy: Never
        name: springboot-microservice
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /config  # 3. Path inside the container where the ConfigMap will be mounted
          name: config-volume  # 2. Reference name for the ConfigMap Volume mount
        - mountPath: /secret  # 4. Path inside the container where the Secret will be mounted
          name: secret-volume  # 2. Reference name for the Secret Volume mount
      volumes:
      - name: config-volume  # 1. Defines a Volume for ConfigMap with a reference name
        configMap:
          name: springboot-microservice-config
      - name: secret-volume  # 1. Defines a Volume for Secret with a reference name
        secret:
          secretName: springboot-microservice-secret