apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-microservice
  name: springboot-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
      - args:
        - -Xmx256m  # Maximum Heap Size
        - -Xms128m  # Initial Heap Size
        - -jar
        - ./app.jar
        command:
        - java
        env:
        - name: APP_GREETING
          value: "Hello from JVM!"
        image: springboot-microservice:maven
        imagePullPolicy: Never
        name: springboot-microservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 512Mi  # Adjusted to be more than 2x the -Xmx value
          requests:
            cpu: "0.5"
            memory: 320Mi  # Adjusted to be more than the -Xms value