apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-microservice
    release: springboot-microservice
  name: springboot-microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-microservice
      release: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
        release: springboot-microservice
    spec:
      containers:
      - args:
        - $(JAVA_OPTS)
        - -jar
        - ./app.jar
        command:
        - java
        env:
        - name: JAVA_OPTS
          value: -Djava.io.tmpdir=/spring-tmp
        - name: SERVER_PORT
          value: "8080"
        image: minikube/springboot-microservice:latest
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 35
          periodSeconds: 20
        name: springboot-microservice
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /spring-tmp
          name: spring-tmp
      imagePullSecrets:
      - name: artifactory
      volumes:
      - emptyDir:
          medium: Memory
        name: spring-tmp