apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-microservice
    release: springboot-microservice
  name: springboot-microservice
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-microservice
    release: springboot-microservice
  type: ClusterIP