apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-microservice
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-microservice
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 15
        type: Utilization
    type: Resource
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max