apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-microservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-microservice
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80