apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-microservice
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-microservice
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 15
        type: Utilization
    type: Resource