apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-microservice
  name: springboot-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
      - args:
        - -jar
        - ./app.jar
        command:
        - java
        env:
        - name: APP_GREETING # This is the environment variable recognized by Spring Boot
          value: "Hello from Kubernetes Environment Variable!"
        - name: APP_API_KEY # This is the environment variable recognized by Spring Boot
          valueFrom:
            secretKeyRef:
              key: api-key
              name: springboot-microservice-secret
        image: springboot-microservice:maven
        imagePullPolicy: Never
        name: springboot-microservice
        ports:
        - containerPort: 8080
          protocol: TCP