apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-microservice
  name: springboot-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
      - args:
        - -jar
        - ./app.jar
        command:
        - java
        env:  #1 Environment variables for the container
        - name: APP_GREETING  #2a Directly setting an environment variable
          value: "Hello from Kubernetes Environment Variable!"
        - name: APP_API_KEY  #2b Setting an environment variable from a Secret
          valueFrom:  #3 Indicates the value is sourced from another object
            secretKeyRef:  #4 Reference to a key within a Secret
              key: api-key  #5 The key within the Secret containing the desired value
              name: springboot-microservice-secret  #6 The name of the Secret
        image: springboot-microservice:maven
        imagePullPolicy: Never
        name: springboot-microservice
        ports:
        - containerPort: 8080
          protocol: TCP