apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-microservice
  name: springboot-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
      - args:
        - -jar
        - ./app.jar
        - --spring.config.location=file:///config/application.properties # 4. Override the default spring configuration location to the mounted ConfigMap path
        command:
        - java
        image: springboot-microservice:maven
        imagePullPolicy: Never
        name: springboot-microservice
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /config  # 3. Path inside the container where the ConfigMap will be mounted
          name: config-volume  # 2. Reference name for the Volume mounts, should match with the Volumes listed below
      volumes:
      - name: config-volume  # 1. Defines a Volume with a reference name
        configMap:  # Specifies that the Volume is a ConfigMap (Intrinsic to Step 1)
          name: springboot-microservice-config  # Name of the ConfigMap to be mounted as a Volume (Intrinsic to Step 1)