apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-microservice
  name: springboot-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-microservice
  template:
    metadata:
      labels:
        app: springboot-microservice
    spec:
      containers:
      - args:
        - -jar
        - ./app.jar
        - --spring.config.location=file:///config/application.properties
        command:
        - java
        image: springboot-microservice:maven
        imagePullPolicy: Never
        name: springboot-microservice
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config-volume
      volumes:
      - name: config-volume
        configMap:
          name: springboot-microservice-config