apiVersion: v1
kind: Service
metadata:
  name: springboot-microservice
  labels:
    app: springboot-microservice
    release: springboot-microservice
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: springboot-microservice
    release: springboot-microservice
